#!/bin/bash
#
# simple console util for translation text to any language using Yandex Translate API
# use: trans.sh 'call me, baby'
# will return translation of a phrase to ru or en language
# more example at http://api.yandex.ru/translate/
#

input=${@//[&]/%26}
link='https://translate.yandex.net/api/v1.5/tr.json/translate?key=trnsl.1.1.20150627T071448Z.117dacaac1e63b79.6b1b4bb84635161fcd400dace9fb2220d6f344ef&lang='
function translate() {
	translated=$(curl -s "$link$key&lang=$1&text=$input" | awk -F'"' {' print $10 '})
}

translate "ru"
if [ "$translated" == "$input" ]
	then
		translate "en"
fi
echo $translated
